[Interface]
# Privatni kljuc kreiran na AUTO na MT-peer
PrivateKey = qJrj8fzfq5GiFdrVBWQkbeVbbkewrKRqcDDiaSqRRGc=
# IP adresa koju ce dobiti klijent
Address = 172.16.10.250/32
# Iskljuci automacko dodavanje
Table = off
# Ovaj rule kaže: svi promet za 172.16.250.0/24 koristi tablicu 100
PostUp   = ip route add 172.16.10.0/24 dev wg0
PostUp   = ip route add 172.16.250.0/24 dev wg0 metric 100
PostDown = ip route del 172.16.10.0/24 dev wg0
PostDown = ip route del 172.16.250.0/24 dev wg0 metric 1000
[Peer]
# Kljuc sa wireguard interfejsa na MT-u
PublicKey = NaOllJJvhoMS/MeqoW23DFZU6EEoDXfcq/xTka3dKSY=
# Mreze koje su omogucene na remote strani za komunikaciju sa klijentom
AllowedIPs = 172.16.10.250/24, 172.16.250.0/24
# IP endpoint-a i port koji gadja
EndPoint = 89.111.232.78:444
PersistentKeepalive = 10