
[Interface]
# Privatni kljuc kreiran na AUTO na MT-peer
PrivateKey = EC3Zks53ZcBZK237fh6R8rqT9AB7TaBYS7kx8SeqC0Y=
# IP adresa koju ce dobiti klijent
Address = 172.16.20.250/32
# Iskljuci automacko dodavanje
Table = off
PostUp   = ip route add 172.16.20.0/24 dev wg1
PostUp   = ip route add 172.16.250.0/24 dev wg1 metric 200
PostDown = ip route del 172.16.20.0/24 dev wg1
PostDown = ip route del 172.16.250.0/24 dev wg1 metric 200
[Peer]
# Kljuc sa wireguard interfejsa na MT-u
PublicKey = BA7GHCJUJSrKyNx4GwBJDUBWiIRXN3jzcBBwUzAojSI=
# Mreze koje su omogucene na remote strani za komunikaciju sa klijentom
AllowedIPs = 172.16.20.250/24, 172.16.250.0/24
# IP endpoint-a i port koji gadja
EndPoint = 89.111.232.250:444
PersistentKeepalive = 10
